// GitHub export — copies the wireframe as GitHub-flavored markdown.
// Drop it into an issue, PR description, or comment.
// No schema JSON — just a human-readable layout summary.

import type { LookyLooSchema } from '../schema/types';
import { isScreenSchema, isFlowSchema } from '../schema/types';

export async function copyAsGithubMarkdown(schema: LookyLooSchema): Promise<void> {
  const lines: string[] = [];

  if (isScreenSchema(schema)) {
    lines.push(`## UI: ${schema.label}`, '');
    lines.push(`**Platform:** ${schema.platform}`, '');
    lines.push('### Layout');
    for (const s of schema.sections) {
      const label = s.label ?? s.type;
      lines.push(`- **${label}** — ${s.contains.join(', ')}`);
      if (s.note) lines.push(`  > ${s.note}`);
    }
  } else if (isFlowSchema(schema)) {
    lines.push(`## Flow: ${schema.label}`, '');
    lines.push(`**Platform:** ${schema.platform}`, '');
    for (const screen of schema.screens) {
      lines.push(`### ${screen.label}`);
      for (const s of screen.sections) {
        const label = s.label ?? s.type;
        lines.push(`- **${label}** — ${s.contains.join(', ')}`);
      }
      lines.push('');
    }
  }

  lines.push('', `<sub>Generated by [Looky Loo](https://github.com/carlostarrats/lookyloo)</sub>`);
  await navigator.clipboard.writeText(lines.join('\n'));
}
